### ISSUE TITLE
Country Flags aren't showing on "chosenEmoji.emoji"

### ISSUE THREAD

**Issue by matheus-garcia** [ealush/emoji-picker-react#146]
Calling most emojis from its objects work as expected, but it seems like flags from countries only appear as letters, for example, when selecting the flag of "Brazil", the `chosenEmoji.emoji` from it shows the letters "BR", the same as other country flags;

![brflag](https://user-images.githubusercontent.com/21963240/81990988-a5016380-9616-11ea-9d13-a07eb1097fb5.PNG)

**Comment by ealush** [comment]
Hey @matheus-garcia, thanks for reaching out. 
Unfortunately there's nothing much you can do about it, this is how Windows renders country flag emojis. You can see an example of it here:

https://emojipedia.org/flags/
Try opening this link from your windows machine and from your smartphone. You will get complete different emojis.

Emojis are actual text your device renders, so it is up to your os to determine how they look. 

The one thing you can do instead is render the emoji at an image tag instead of a string.

Hope that clarifies it a bit.

**Comment by matheus-garcia** [comment]
I see, thanks.
