### ISSUE TITLE
State is undefined on child component callback

### ISSUE THREAD

**Issue by mflash123** [ealush/emoji-picker-react#152]
Parent component:
```
const [value, setValue] = useState();
...
const someAction = () => {
setValue(123)
}

const emojiHandle = () => {
console.log(value) //display undefined
}
...
...
return(
...
<Emoji callback={handleEmojiChange} /> // -> child component :  onEmojiClick={callback}
<button onClick={someAction}>Press me 1st</button>
)
```

So, problem is that State is undefined on child component callback.
**Reproduction:**
Press the button to set state.
Then press on any Emojy to execute callback from parent component and display state.
Callback will show undefined state, which you already set when you press the button.

How to get access to state?

**Comment by ealush** [comment]
Hey, I am trying to reproduce with your example but I am not sure I am experiencing the bug. Would you mind sharing forking this blitz and sharing what you experience?
https://stackblitz.com/edit/emoji-picker-react-gxa6r9?file=index.js

click fork at the top:
![image](https://user-images.githubusercontent.com/11255103/82590337-35efb600-9ba6-11ea-88e7-7ba73ba1f70e.png)

**Comment by mflash123** [comment]
> Hey, I am trying to reproduce with your example but I am not sure I am experiencing the bug. Would you mind sharing forking this blitz and sharing what you experience?
> https://stackblitz.com/edit/emoji-picker-react-gxa6r9?file=index.js
> 
> click fork at the top:
> ![image](https://user-images.githubusercontent.com/11255103/82590337-35efb600-9ba6-11ea-88e7-7ba73ba1f70e.png)

Thanks for reply.
I post a code:
https://stackblitz.com/edit/emoji-picker-react-uxwzsl

**Comment by ealush** [comment]
I see. this is really weird. I will have to debug this. Thanks for reporting.

**Comment by j-edward** [comment]
Is there any update on this?

**Comment by jlevy-io** [comment]
I slightly adjusted your code and it seems to work this way.   Not sure if it is due to memoization perhaps.

[https://emoji-picker-react-jakfvz.stackblitz.io](https://emoji-picker-react-jakfvz.stackblitz.io)

**Comment by LetHergo** [comment]
yes, I also have this problem.
onEmojiClick callBack can not get props value 
@ealush

**Comment by zpzxgcr** [comment]
yes, I also have this problem.
onEmojiClick callBack can not get props value
@ealush

**Comment by ealush** [comment]
Hey guys, sorry for taking so long with this.

I believe that the latest version (3.2.3) should solve this issue.

For anyone interested in the details: https://github.com/ealush/emoji-picker-react/commit/2e19179a93303c0a51d48fded49fc98ea8712c5f

The picker had two bugs that caused this unexpected behavior.

1. Stored the consumer's onClick handler in the `useReducer` hook as an initial value, meaning that it never got refreshed past the initial render - so it always stuck with the first initial scope references. But fixing this was not enough because:
2. Some of the emoji components are memoized, so they only kept reference to the recent-render handler, which lead to outdated scope variables. Now I store your click handler inside a ref, and always access the function from there.

These two seem to solve the issue, can anyone please post back to see if it works.

**Comment by paladin952** [comment]
I still face this issue on 4.5.1

**Comment by ealush** [comment]
Hey @paladin952 this is a closed and old issue. Can you please create a new issue with reproduction steps?
