### ISSUE TITLE
Error while fetching three images.

### ISSUE THREAD

**Issue by matheus-garcia** [ealush/emoji-picker-react#157]
There are three images there are getting an error on console.

https://cdn.jsdelivr.net/gh/iamcal/emoji-data@master/img-apple-64/2640-fe0f.png
https://cdn.jsdelivr.net/gh/iamcal/emoji-data@master/img-apple-64/2642-fe0f.png
https://cdn.jsdelivr.net/gh/iamcal/emoji-data@master/img-apple-64/2695-fe0f.png

I don't think this impact on the component, but I'm curious, would this component work on a intranet?

**Comment by ealush** [comment]
Hey,
So this has two parts.

1. When connected to the internet, you will not see a blank emoji. When emojis fail to load, I just remove them from the list altogether.
2.The emojis do not come with the package itself, but instead are served via cdn. Otherwise, in most cases, it would just be too heavy and too slow.

On an intranet, you'll have to self host the emojis, and provide the url for it. These are the steps to do it:
a. Download an emoji library from a place like https://github.com/iamcal/emoji-data/tree/master/img-apple-64
b. when rendering the picker, add an emojiUrl prop with the image location, currently: https://cdn.jsdelivr.net/gh/iamcal/emoji-data@master/img-apple-64

```
<EmojiPicker emojiUrl="https://cdn.jsdelivr.net/gh/iamcal/emoji-data@master/img-apple-64"/>
```

You'll need to provide a different url from within the intranet.

**Comment by matheus-garcia** [comment]
Thanks, is there a way to check if the images from the emoji itself didn't load?

**Comment by ealush** [comment]
So basically, as I said, I listen to these load failures and remove those from state. What you _can_ do is basically attach an event listener to the picker and listen to load errors.
