### ISSUE TITLE
on Focus Out

### ISSUE THREAD

**Issue by CeoFred** [ealush/emoji-picker-react#164]
To Improve user experience on some applications, the emoji picker needs to be closed when it loses its focus, it can be an opt in feature though... If this already exist please let me know or i can work on this as well.

**Comment by ealush** [comment]
Hey @CeoFred, thanks for opening this issue :)

Not sure what your expected behavior is, though. The picker does not have show/hide capabilities. Instead, this is on the consumer side alone to determine when and how to show it. One might want it inside a popever, and the other might want it as an inline component, or in a sidebar - so the visibility side is completely out of the hands of the picker it self. I hope this makes sense.
