### ISSUE TITLE
Recently used displaying incorrect skin tone

### ISSUE THREAD

**Issue by tompliner** [ealush/emoji-picker-react#190]
When you trigger the variation menu for an emoji and select a skin tone, the recently used section displays the lightest skin tone or the yellow version. However when you select a skin tone first and then pick an emoji, the recently used section displays the correct skin tone.

**Comment by ealush** [comment]
Yep, that looks like a bug. Thanks r reporting that.
It might take me some time to get around to fixing it. Feel free to take a stab at it yourself if you get to it before me.

**Comment by tompliner** [comment]
I think replacing lines 26 - 29 of https://github.com/ealush/emoji-picker-react/blob/master/src/lib/recentlyUsed/index.js with
```
  const unifiedParts = unified.split( '-' );

  let skinVariation = '';

  if ( unified !== originalUnified && unifiedParts.length > 1 ) {
    skinVariation = unifiedParts[1];
  }
```
fixes it - I looked through a table of unified codes online and the second chunk seems to always be the skin tone modifier, but there are a lot of emoji and it's possible I missed some that don't conform to that.

**Comment by ealush** [comment]
@tompliner this seems to work for the majority of the emojis, and as you noted - there may be some exceptions, but this is still significantly better than it used to be.

I released your fix with a slight change to how I reference the variation state, because it seemed to keep it in the localstorage twice, but other than that - it works flawlessly.

It's now live in emoji-picker-react@3.4.7.

Thank you!

**Comment by ealush** [comment]
LMK if this can be closed now.

**Comment by tompliner** [comment]
Perfect! Thank you!!
