### ISSUE TITLE
Troubles with country emoji

### ISSUE THREAD

**Issue by Holenvik** [ealush/emoji-picker-react#193]
Hi, thanks a lot for this utility
I opened your link with demo and when you select country flag there is only letters and you won't be able to see emoji
https://stackblitz.com/edit/emoji-picker-react?file=index.js

Also when I installed this inside my project with latest version I had same issue

**Comment by ealush** [comment]
Hey @Holenvik,
Here's what I see on my end: 
![image](https://user-images.githubusercontent.com/11255103/119620331-89c25a00-be0d-11eb-9984-5db24d8f00b3.png)

I believe what you're seeing is simply how windows renders the country emojis. You can omit the `native` prop to use images instead of relying on your OS for rendering.

**Comment by Holenvik** [comment]
@ealush 
Maybe you know a solution for this issue, when I past Flag emoji to the input or inside <div> on Windows, then I can't see flag, only string, but if I open site on Android as one of variant, then okay

**Comment by ealush** [comment]
This is exactly the issue I described. Each OS has its own emoji display. Windows uses text, and android renders it as flags. The only solution is to render them as images, which won't work for inputs, but will work for divs.

**Comment by Holenvik** [comment]
Thank you, I understood
