### ISSUE TITLE
show select emoji only

### ISSUE THREAD

**Issue by ak34504** [ealush/emoji-picker-react#216]
I want to show only selected (5-6) emoji like reactions.how we can achieve this...

**Comment by diegobonagurio** [comment]
@ak34504 what did you do?

**Comment by ealush** [comment]
The picker now supports a reactions picker capability:


![image](https://github.com/ealush/emoji-picker-react/assets/11255103/48901306-e7fd-49cd-8f1e-9b214083a61d)

![reactions](https://github.com/ealush/emoji-picker-react/assets/11255103/38a9c652-ee2e-43d4-b0e6-33735f1bcbe7)

The picker can be used as a reactions picker. To use it as a reactions picker, you should set the reactionsDefaultOpen prop to true. This will cause the picker to the reactions picker on the initial mount instead of the main picker component.

To customize the reactions, you should pass an array of unified emoji ids to the reactions prop.

The reactions picker uses the same event handlers, and the same css variables for customizations.

```jsx
<Picker reactionsDefaultOpen />
```
