### ISSUE TITLE
the package is really nice but its too slow when am integrating it with my react app.

### ISSUE THREAD

**Issue by codecracker05** [ealush/emoji-picker-react#224]
the package is really nice but its too slow when am integrating it with my react app. It takes more time to load the picker popup as well as am getting the error in console too. May i know why it takes so long to show the popup. Here by i will attach the scrrenshot of what am getting in my console.
![Screenshot 2022-01-10 at 5 46 08 PM](https://user-images.githubusercontent.com/96469935/148764326-a3c36d33-f8ba-4549-b28e-757bc62660cc.png)

**Comment by ThinhNguyenHoang** [comment]
Same, My project is not bombarded by errors like yours but It is still to slow (since the package fetch the emoji list from the internet, I believe).  

Tons of request are made:
![image](https://user-images.githubusercontent.com/60644156/155984624-c1c3b4b8-afc1-40e9-bbd3-0be7c00875ca.png)

I don't know if it is possible but I think the emoji should be stored as text and display as is to reduce load time of the picker (although the package will be huge but I think it is worth the trade-off)

**Comment by ealush** [comment]
@edisoni1995, that image, if you look closely, is awfully low res and hard to work with. I've used it before in one of the earliest versions of the picker, and eventually had to give up on it because the scaling didn't work well, and the emojis didn't look nice.

**Comment by vfal-lab** [comment]
WhatsApp is also using them the same way with images but instead of having them all in one single image, they have separated every category into a small image grouping 20-30 icons into one single image. Even if you keep using them the same way with images for each icon at least those icons can be compressed better (Telegram has the implementation the same way but their icons are 2-3KB which makes a huge difference when you have hundreds of requests)

**Comment by edisoni1995** [comment]
WhatsApp is also using them the same way with images but instead of having them all in one single image, they have separated every category into a small image grouping 20-30 icons into one single image. Even if you keep using them the same way with images for each icon at least those icons can be compressed better (Telegram has the implementation the same way but their icons are 2-3KB which makes a huge difference when you have hundreds of requests)

**Comment by hugomallet** [comment]
Why not a system font by default ? What is the number of items ?

**Comment by ealush** [comment]
> WhatsApp is also using them the same way with images but instead of having them all in one single image, they have separated every category into a small image grouping 20-30 icons into one single image. Even if you keep using them the same way with images for each icon at least those icons can be compressed better (Telegram has the implementation the same way but their icons are 2-3KB which makes a huge difference when you have hundreds of requests

@edisoni1995 whatsapp has the capacity and ability to maintain their own sprite. All I have is the emoji-data sprite.

Seems like you have really looked into it. Would you like taking a look and try to implement it here? You have my support, and I can offer help with the codebase.

**Comment by tettoffensive** [comment]
@ealush Is there a way the library could just load images as they scroll into view? I know there's a lazyLoading parameter, but it's still pretty slow loading all of those images

**Comment by TheMacros** [comment]
I'm using your picker on one of my projects, it works fine. 
But there is the real problem with thousands of images. Some of our clients argue that the app completely crashes when an emoji picker appears on the mobile (low-end) device. Also, it works very laggy on low-end devices. So, you really need to use one image instead of ~1800 images (about 9,5 MB of traffic once the picker is opened) https://www.screencast.com/t/KSZLYEb5
Yes, your images are highest quality than this one https://unpkg.com/emoji-datasource-apple@5.0.1/img/apple/sheets-256/64.png but then you need to compose all your images into one image. It should improve performance a lot.

**Comment by WillTaylor22** [comment]
I want to say a big thank you to EaLush for the package.
For us, we ran in to the same issue mentioned here.

Setting emojiStyle='native' worked really well for us.

**Comment by TheMacros** [comment]
> I want to say a big thank you to EaLush for the package. For us, we ran in to the same issue mentioned here.
> 
> Setting emojiStyle='native' worked really well for us.

Thanks, it's really works faster with emojiStyle='native'.
