### ISSUE TITLE
Native emojies disintegration 

### ISSUE THREAD

**Issue by MahdiMhqq** [ealush/emoji-picker-react#226]
When you turn on the native emoji support & the desired emoji has a length of more than 2 (each emoji has a length of 2), it causes disintegration in the emoji list.
The image below is a snapshot of the issue.

I guess if there is a way to assign two squares to emojis with a length of more than 2, it will resolve the issue

![image](https://user-images.githubusercontent.com/90528664/149625571-9545adef-4e02-4fc7-80ae-95bb225cbf44.png)

**Comment by MahdiMhqq** [comment]
Also i forgot to mention that i'm using version 3.5.0 of emoji-picker-react and this bug occured when i was using native option on windows device.

Also there is some unknown/unsupported charecters (white square charecter) on emoji list. If we can filter them out it looks so much better. 
Cheers 🍻

**Comment by MahdiMhqq** [comment]
Any update on this issue? @ealush

**Comment by ealush** [comment]
@MahdiMhqq, sorry for replying late.
Unfortunately, there's nothing much I can do, other than suggest you to use env-specific images rather than the native emojis. The reason is that native emojis are rendered by the OS, and there's nothing much we can do.

If you care about displaying the correct emoji style based on the OS, the same emojis exist as images on the CDN, and you can provide the url to them after detecting (on your end) which OS it is.
