### ISSUE TITLE
404 Error when SYMBOLS are scrolled in emoji picker

### ISSUE THREAD

**Issue by karthikreddi** [ealush/emoji-picker-react#245]
**Description:**
  404 Error when SYMBOLS emojis are scrolled in this emoji picker

**Error:** 
  2640-fe0f.png:1          GET https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/2640-fe0f.png 404

**Comment by alexisRojas99** [comment]
what is the solution? I have the same problem

**Comment by ealush** [comment]
Hey,
This is not something you should be worried of and is completely expected.

When rendering the images, some imagesbmay be missing on the CDN or fail to load due to network issue.

The picker corrects itself by removing the images, so they should not appear broken and the log you get is the only symptom.
