### ISSUE TITLE
Not Responsive Friendly

### ISSUE THREAD

**Issue by tusharpamnani** [ealush/emoji-picker-react#352]
Hi!
I was building a fully responsive chat application but while working, I found it tremendously difficult to make it mobile friendly.

**Comment by ealush** [comment]
I recommend not to use this component in mobile for various reason. Mainly, because the native OS keyboard already has a fully capable and performant emoji-picker.

Apart from that, loading this complex and heavy component on a mobile device, with slow connectivity can be bad on performance as well. The interactions are designed to be keyboard/mouse first. Anything else is coincidental.
