### ISSUE TITLE
Accessible names of icons

### ISSUE THREAD

**Issue by Dominiczeq7** [ealush/emoji-picker-react#381]
There is need to have better aria-labels for some icons like flags. For example `aria-label="flag-pl"` is not very accessible.

**Comment by ealush** [comment]
Hm. Not sure how to handle this. Emoji names are provided by the js-emoji library. An option would be to just use all names in the label, but that might be a little bit excessive.

**Comment by DGG-IVY** [comment]
@ealush  I have idea how to handle this. Let's look at `ClickableEmojiButton.tsx`. We have:
```
      aria-label={emojiNames[0]}
      data-full-name={emojiNames}
```

We can change to this:
```
      aria-label={emojiNames[0].match('flag-') ? emojiNames[1] : emojiNames[0]}
      data-full-name={emojiNames}
```

Because in data-full-name there is list of two values and we can catch case when flag name is used and use the second one.
![image](https://github.com/ealush/emoji-picker-react/assets/114407441/b349876c-d1d6-46a5-bb3c-8742b525a3ac)


Can I make PR to push this change?

**Comment by Dominiczeq7** [comment]
@ealush Can you merge this please? https://github.com/ealush/emoji-picker-react/pull/393

BTW. @DGG-IVY is my second account - I forgot to relogin
