### ISSUE TITLE
hiddenEmojis vs suggested Emojis

### ISSUE THREAD

**Issue by lexpierini** [ealush/emoji-picker-react#419]
The list of codes passed in the hiddenEmojis property does not affect the suggested emojis. I have a situation where I've hidden some emojis that aren't working. However, they are displayed in the client's list of suggested emojis. Shouldn't the rule for hiding emojis also apply to the list of suggested emojis?

"react": "^18.2.0",
"emoji-picker-react": "^4.10.0",

**Comment by ealush** [comment]
Yeah, that's the main drawback with the current implementation. If they have it stored in local storage because they used it before we currently don't filter them.

The assumption is that new users won't get them to begin with so they won't show up in the suggestions as well, and if they've already used it before adding the rule a that will be an edge case.

We can filter those out as well technically, but I don't see it as a major concern.
