### ISSUE TITLE
The href='#!' attribute in the Emoji class is triggering a full app re-render with react router 4

### ISSUE THREAD

**Issue by bnenu** [ealush/emoji-picker-react#50]
Clicking on an emoji changes the router location by adding the "#!" which then triggers re-render on all router dependent components (React Router 4.4.0, react-router-dom 4.4.2, emoji-picker-react 1.7.1, react 16)

**Comment by ealush** [comment]
Hey @bnenu, thanks for submitting this issue.
This seems to be related to: https://github.com/ealush/emoji-picker-react/issues/38

In [1.6.1](https://github.com/ealush/emoji-picker-react/commit/7e90ee96bcb90ae9f8b4b373c87db7d993126612) I added the ability to get the event from the Emoji Click. 

Can you try calling `event.preventDefault()` in your `onEMojiClick` callback event?
```js
onEmojiClick(id, emojiObject, event) {
   event.preventDefault();
   // [... your code here]
}
```

**Comment by ealush** [comment]
@bnenu 

There you go:
https://github.com/ealush/emoji-picker-react/releases/tag/1.7.2
feel free to update to 1.7.2

```npm install --save 1.7.2```

**Comment by ealush** [comment]
Pushed 2.0.2 as well.

**Comment by bnenu** [comment]
Hi, 2.0.2 is working now as expected. Many thanks for the quick reply. 

I do have one question, is there a special reason you used an 'a' tag with a href attribute for the emoji, as far as I can tell you could have used any element with a 'onclick' handler?

**Comment by ealush** [comment]
@bnenu 

> Hi, 2.0.2 is working now as expected. Many thanks for the quick reply.
Hey, no problem. I'm glad that it worked.

> I do have one question, is there a special reason you used an 'a' tag with a href attribute for the emoji, as far as I can tell you could have used any element with a 'onclick' handler?

Yes. It is more correct, semantically speaking, to use a clickable elements for clickable parts of your app - even though it could work without it. My mistake was using an anchor tag (`<a/>`) instead of the more semantically correct `<button/>` element which is more suitable for non-navigable clickable elements - and wouldn't have caused that bug in the first place.

In the next major (3) I am planning to change the markup and replace all anchors with buttons.

**Comment by ealush** [comment]
Hm. I was not aware of this change. I'll look into their new API and if needed, modify the docs accordingly. Thanks!
