### ISSUE TITLE
Search on mobile returns no results

### ISSUE THREAD

**Issue by lunch-meat** [ealush/emoji-picker-react#70]
Both in my app and on a mobile browser in the demo (https://ealush.github.io/emoji-picker-react/), searching returns no results

**Comment by ealush** [comment]
Hey @lunch-meat, sorry for taking the time. Thank you for letting me know of the bug 👍 

I believe that the problem is not mobile-vs-desktop, but case sensitivity. All emoji names are lower cased and usually, mobile devices capitalize the first letter. I wasn't making a case-insensitive search, so it showed nothing on mobile.

I published 2.0.5 that should fix it.
