### ISSUE TITLE
Get actual emoji in returned object

### ISSUE THREAD

**Issue by oznekenzo** [ealush/emoji-picker-react#87]
Hey!  I love the component, but I'm wondering why you can't also add the actual emoji selected and add it to the returned object when you pick the emoji?

Having to render an image from a CDN for every emoji you want to render seems too expensive...

**Comment by ealush** [comment]
Hey @oznekenzo, thanks for your interest in this project :)

The reason I don't return the actual emoji is that it simply isn't reliable enough to be cross-platform, and in many cases, you wouldn't be able to work with it as not all emojis are supported by all operating systems. That's why the standard on the web is to use an image over the emoji character.

But here is a neat trick you can do to actually try and get the emoji yourself from the return object:

```js
const emojiCode = '1f43d';
String.fromCodePoint(parseInt(emojiCode, 16));
// "🐽"
```

![image](https://user-images.githubusercontent.com/11255103/49544215-f4e8e080-f8e2-11e8-8001-47113be72954.png)

I hope that helps :)
