### ISSUE TITLE
Differences between picker and parser?

### ISSUE THREAD

**Issue by rmdevos** [ealush/emoji-picker-react#95]
I'm using emoji-picker-react together with emoji-js in a project and I want to put the emoji images on a CDN. I am having issues however, since images are missing.

Emoji :runner: for example. When I inspect the image URL in  the picker it is the following URL:

```https://cdn.jsdelivr.net/emojione/assets/3.0/png/32/1f3c3.png``` (which exists)

The parser (emoji-js) however generates the following URL:

```https://cdn.jsdelivr.net/emojione/assets/3.0/png/32/1f3c3-200d-2642-fe0f.png``` (which does not exist)

I am using the following version:
```
                "emoji-js": "^3.4.1",
                "emoji-picker-react": "^2.1.1",
```

**Comment by ealush** [comment]
Hey @rmdevos, thanks for posting this issue, and I am sorry that you are experiencing it. I'll try to give you a brief explanation on why it is happening, and maybe assist with a workaround that should work for you.

## Why is this happening to me?
In order to make emoji-picker-react configuration free, and so you don't need to worry about hosting the images yourself, I used a free CDN hosting the emojione images. Apparently it uses a slightly different convention than emoji-js which creates these discrepancies. This mostly affects the compound emojis with more than one attribute.

## How can I fix it?
Emojione stopped being free, so it is hard finding a good up-to-date cdn with their emojis (I might end up switching to Apple), but I did manage to find a solution - use emoji-js's own repo. It since has been deleted, but luckily, everything on the internet stays forever.

So - When configuring emoji-js, instead of using the url I supplied ([documentation link](https://github.com/ealush/emoji-picker-react#integrating-with-your-app)), do this:

```js
jsemoji.img_sets.emojione.path = 'https://cdn.jsdelivr.net/gh/iamcal/emoji-data@19299c91bc87374118f06b2760f1ced69d714ab1/img-emojione-64/';
```

I tried it on a couple of emojis, including the one that didn't work for you, and it seemed to work well.

Can you please try using this url and let me know if it works for you as well?

I hope that helps.

**Comment by rmdevos** [comment]
Hi @ealush.

Thanks for your help. I was able to get the emojis from the specific git commit (19299c91bc87374118f06b2760f1ced69d714ab1) you posted. 

That way we can host the emojis on our own CDN without any discrepancies.

You're a star
